-- Active: 1783153481263@@127.0.0.1@5432@sdspaljabbar
CREATE SCHEMA IF NOT EXISTS SPMB;

CREATE SCHEMA IF NOT EXISTS PD;
CREATE SCHEMA IF NOT EXISTS PTK;
CREATE SCHEMA IF NOT EXISTS RECRUITMENT;
CREATE SCHEMA IF NOT EXISTS ROMBEL;
CREATE SCHEMA IF NOT EXISTS MASTER;